const EDUCATION_LEVELS = {
  INCOMPLETE_ELEMENTARY_SCHOOL: 'ENSINO FUNDAMENTAL INCOMPLETO',
  ELEMENTARY_SCHOOL: 'ENSINO FUNDAMENTAL COMPLETO',
  INCOMPLETE_HIGHSCHOOL: 'ENSINO MÉDIO INCOMPLETO',
  HIGHSCHOOL: 'ENSINO MÉDIO COMPLETO',
  INCOMPLETE_COLLEGE: 'ENSINO SUPERIOR INCOMPLETO',
  COLLEGE: 'ENSINO SUPERIOR COMPLETO'
};

const INCOME_SOURCES = {
  SALARIED: 'ASSALARIADO',
  INDEPENDENT: 'AUTONOMO',
  PUBLIC_EMPLOYEE: 'PÚBLICO'
};

const PERSONAS = {
  mother: 'Mãe',
  child: 'Filho ou Filha',
  spouse: 'Cônjuge',
  sibling: 'Irmão ou Irmã',
  father: 'Pai'
};

const PROPERTY_TYPES = {
  APARTMENT: 'Apartamento',
  HOME: 'Casa',
  BUILDING: 'Comercial'
};

const RESIDENTS = {
  OWN: 'Próprio',
  THIRD_PARTIES: 'Terceiros'
};

const MARITAL_STATUS = {
  MARRIED: 'CASADO',
  REGISTERED_STABLE_UNION: 'UNIÃO ESTÁVEL REGISTRADA',
  NOT_REGISTERED_STABLE_UNION: 'UNIÃO ESTÁVEL NÃO REGISTRADA',
  SINGLE: 'SOLTEIRO',
  DIVORCED: 'DIVORCIADO',
  WIDOWER: 'VIÚVO'
};

const PROPERTY_AGE = ['<=2', '3-5', '6-10', '11-20', '21-30', '31-40', '41-50', '>=51'];

const BEDROOMS = ['0', '1', '2', '3', '4', '5', '6', '7', '8'];

const SUITES = [...BEDROOMS];

const GARAGES = ['0', '1', '2', '3', '4', '5+'];

const suitesOptions = bedrooms => SUITES.slice(0, bedrooms + 1);

const PHONE_REG_EXP = /^(\+\d{2}\d{2})(\d{4,5}\d{4})$/;

module.exports = {
  MARITAL_STATUS,
  EDUCATION_LEVELS,
  PROPERTY_TYPES,
  PROPERTY_AGE,
  BEDROOMS,
  suitesOptions,
  PERSONAS,
  GARAGES,
  INCOME_SOURCES,
  RESIDENTS,
  PHONE_REG_EXP
};
