const MIN_LOAN_VALUE = 30000;
const MIN_PROPERTY_VALUE = 200000;
const MIN_AGE = 18;
const MAX_AGE = 75;

const LOAN_MOTIVATION = [
  'PAY_OFF_DEBTS',
  'OPEN_OWN_BUSINESS',
  'INVESTING_OWN_BUSINESS',
  'FUND_STUDIES',
  'RENOVATE_HOUSE',
  'PAY_MARRIAGE',
  'ANOTHER_REASON',
  'JUST_CURIOSITY'
];

const TERMS = [60, 90, 120, 150, 180, 210, 240];

const GRACE_PERIOD = [0, 1, 3, 6];

module.exports = {
  MIN_LOAN_VALUE,
  MIN_PROPERTY_VALUE,
  MIN_AGE,
  MAX_AGE,
  LOAN_MOTIVATION,
  TERMS,
  GRACE_PERIOD
};
