version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7

    commands:
      - pip install awscli aws-sam-cli==1.19.1
      - sam --version

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ./install-layer-deps.sh
      - sam build --debug
      - sam package --debug --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file ./serverless-output.yaml

artifacts:
  files:
    - template.yaml
    - serverless-output.yaml
    - configuration.json
