AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pontte API

Parameters:
  Project:
    Description: Project Name
    Type: String
    Default: API

  Environment:
    Description: Execution environment
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring

Conditions:
  Prod: !Equals [!Ref Project, prod]

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 1024
    Timeout: 120
    Layers:
      - !Ref CommonAPILayer
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
    Environment:
      Variables:
        PROJECT: !Ref Project
        ENV: !Ref Environment
        ES_ENDPOINT: !FindInMap [Config, !Ref Environment, esEndpoint]

Resources:


  CommonAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Common libraries
      ContentUri: src/layers/common
      CompatibleRuntimes:
        - nodejs10.x

  ApiAuditLogApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/audit/template.yaml
      Parameters:
        Project: !Ref Project
        Environment: !Ref Environment

  ApiApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/api/template.yaml
      Parameters:
        Environment: !Ref Environment
        DBClients: !Ref DBClients
        CommonAPILayer: !Ref CommonAPILayer

  ApiECredApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/eCred/template.yaml
      Parameters:
        Environment: !Ref Environment
        DBClients: !Ref DBClients
        CommonAPILayer: !Ref CommonAPILayer


  DBClients:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ClientsApi.${Environment}'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [Prod, true, false]
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH
      Tags:
        - { Key: Project, Value: !Ref Project }
        - { Key: Environment, Value: !Ref Environment }
