AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pontte API

Parameters:
  Project:
    Description: Project Name
    Type: String
    Default: API

  Environment:
    Description: Execution environment
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring

Conditions:
  Prod: !Equals [!Ref Project, prod]

Mappings:
  Config:
    test:
      esEndpoint: 'test'
    dev:
      esEndpoint: 'https://search-simulations-dev-utjmngpwpsdremjdqo2cupssmy.us-east-1.es.amazonaws.com'
    staging:
      esEndpoint: 'https://search-simulations-staging-44arqulu2bq6mmk7lfmramwv3u.us-east-1.es.amazonaws.com'
    prod:
      esEndpoint: 'https://search-simulations-prod-ckbzwabelmgkkrbvpyuio2lq6y.us-east-1.es.amazonaws.com'

Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 1024
    Timeout: 120
    Layers:
      - !Ref CommonAPILayer
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
    Environment:
      Variables:
        PROJECT: !Ref Project
        ENV: !Ref Environment
        ES_ENDPOINT: !FindInMap [Config, !Ref Environment, esEndpoint]

Resources:

  DBClients:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ClientsApi.${Environment}'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [Prod, true, false]
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH
      Tags:
        - { Key: Project, Value: !Ref Project }
        - { Key: Environment, Value: !Ref Environment }

   :
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Common libraries
      ContentUri: src/layers/common
      CompatibleRuntimes:
        - nodejs14.x

  ApiAuditLogApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/audit/template.yaml
      Parameters:
        Project: !Ref Project
        Environment: !Ref Environment
        CommonAPILayer: !Ref CommonAPILayer

  ApiApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/api/template.yaml
      Parameters:
        Environment: !Ref Environment
        ESEndpoint: !FindInMap [Config, !Ref Environment, esEndpoint]
        DBClients: !Ref DBClients
        CommonAPILayer: !Ref CommonAPILayer

  ApiECredApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: src/eCred/template.yaml
      Parameters:
        Environment: !Ref Environment
        ESEndpoint: !FindInMap [Config, !Ref Environment, esEndpoint]
        DBClients: !Ref DBClients
        CommonAPILayer: !Ref CommonAPILayer
