AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Function that handle audit logs

Parameters:
  Project:
    Type: String
    Default: Api

  Environment:
    Description: Execution environment
    Type: String
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - refactoring

Conditions:
  Prod: !Equals [!Ref Project, prod]

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 1024
    Timeout: 120
    Layers:
      - !Ref ApiCommonLayer
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
    Environment:
      Variables:
        PROJECT: !Ref Project
        ENV: !Ref Environment

Resources:
  ApiCommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: common libraries
      ContentUri: ../layers/common
      CompatibleRuntimes:
        - nodejs10.x

  ApiReceiverAuditLogFn:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub 'ApiReceiverAuditLogFn-${Environment}'
      Description: Collect data with SQS and save in database
      Handler: receiver.handler
      Tracing: Active
