AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API

Parameters:
  Project:
    Type: String
    Default: Api

  Environment:
    Description: Execution environment
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

  ESEndpoint:
    Description: Elastcsearch Endpoint
    Type: String

  DBClients:
    Description: Ref of DBClients
    Type: String

  CommonAPILayer:
    Description: Ref of CommonAPILayer
    Type: String

Conditions:
  Prod: !Equals [!Ref Environment, prod]
  Staging: !Equals [!Ref Environment, staging]

Mappings:
  Config:
    test:
      esEndpoint: 'test'
    dev:
      domain: 'apidev.pontte.com.br'
      esEndpoint: 'https://search-simulations-dev-utjmngpwpsdremjdqo2cupssmy.us-east-1.es.amazonaws.com'
    staging:
      domain: 'sandbox.pontte.com.br'
      esEndpoint: 'https://search-simulations-staging-44arqulu2bq6mmk7lfmramwv3u.us-east-1.es.amazonaws.com'
    prod:
      domain: 'api.pontte.com.br'
      esEndpoint: 'https://search-simulations-prod-ckbzwabelmgkkrbvpyuio2lq6y.us-east-1.es.amazonaws.com'

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 1024
    Timeout: 120
    Layers:
      - !Ref CommonAPILayer
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
    Environment:
      Variables:
        PROJECT: !Ref Project
        ENV: !Ref Environment
        ES_ENDPOINT: !Ref ESEndpoint
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"

Resources:
  APIDomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      DomainName:
        !If [Prod, "api.pontte.com.br", !If [Staging, "sandbox.pontte.com.br", !Sub "api${Environment}.pontte.com.br"]]
      CertificateArn: "arn:aws:acm:us-east-1:848638426587:certificate/639f5ab2-c77a-4f62-8250-c85716a6753f"

  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'API-${Environment}'
      StageName: !Ref Environment

  APIMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref API
      Stage: !Ref API.Stage

  SimulationSaveApiFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "SimulationSaveApiFn-${Environment}"
      Description: Save the simulations done from partners
      CodeUri: simulation
      Handler: simulation.handler
      Tracing: Active
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub 'cognito/${Environment}/*'
        - SQSSendMessagePolicy:
            QueueName: !Sub "ApiAuditLog_${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Simulations.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Ref DBClients
        - DynamoDBCrudPolicy:
            TableName: !Sub "People.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Contract.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Entity.${Environment}"
        - LambdaInvokePolicy:
            FunctionName: !Sub 'SimulatorCalculatorFn-${Environment}'
        - LambdaInvokePolicy:
            FunctionName: !Sub 'CepGetFn-${Environment}'
      Events:
        api1:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: "/v1/simulation"
            Method: POST

  ContractSaveApiFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ContractSaveApiFn-${Environment}"
      Description: Save the contract done from partners
      CodeUri: contracts
      Handler: contract.handler
      Tracing: Active
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub 'cognito/${Environment}/*'
        - SQSSendMessagePolicy:
            QueueName: !Sub "ApiAuditLog_${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Contract.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Ref DBClients
        - DynamoDBCrudPolicy:
            TableName: !Sub "People.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Property.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Simulations.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "User.${Environment}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "Process.${Environment}"
        - LambdaInvokePolicy:
            FunctionName: !Sub 'CepGetFn-${Environment}'
        - DynamoDBCrudPolicy:
            TableName: !Sub "Entity.${Environment}"
        - Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Action:
                - 'cognito-idp:AdminCreateUser'
              Resource: '*'
      Events:
        api1:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: "/v1/contract"
            Method: POST
