name: Deploy Alert

on:
  push:
    branches:
      - master
      - staging
      - develop

jobs:
  InformDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        run: >
          curl -X POST \
            -H "Content-type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN_GIT_ACTION }}" \
            -d '{
              "channel": "C010FF5DQ72",
            "text": ":ship: '$(echo $GITHUB_REF|cut -f3 -d/)'
           :package: ['$(echo $GITHUB_REPOSITORY|cut -f2 -d/)']
           :bust_in_silhouette: '${GITHUB_ACTOR}$(
            grep -q master <<< "$GITHUB_REF" && echo "\nDEPLOY EM PROD\nhttps://gfycat.com/ifr/search/thumbs-up?_=${{ github.run_id }}")'
            "}' \
            https://slack.com/api/chat.postMessage
            