name: Integration

on: 
  workflow_dispatch:
    inputs:
      apiEnv:
        description: Env
        required: true
        default: dev

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64
      - name: Downlaod karate
        working-directory: packages/tests
        run: curl -L https://github.com/intuit/karate/releases/download/v0.9.6/karate-0.9.6.jar > karate.jar

      - name: Test
        run: java -Dkarate.env=${{ github.event.inputs.apiEnv }} -cp karate.jar com.intuit.karate.Main **/*.feature