name: Integration

on: 
  workflow_dispatch:
    inputs:
      apiEnv:
        description: Env
        default: dev
      apiLogin:
        description: API login (clientId)
      apiPass:
        description: API password (clientSecrectKey)
      apiECredLogin:
        description: API ECred login (clientId)
      apiECredPass:
        description: API ECred password (clientSecrectKey)

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64

      - name: Downlaod karate
        run: npx lerna run pre:test:integration --scope=api-tests

      - name: Test
        run: npx lerna run test:integration --scope=api-tests
        env:
          TEST_ENV: ${{ github.event.inputs.apiEnv }}
          API_CLIENT: ${{ github.event.inputs.apiLogin || secrets.API_TEST_CLIENT_ID }}
          API_SECRET_KEY: ${{ github.event.inputs.apiPass || secrets.API_TEST_SECRET_KEY }}
          ECRED_API_CLIENT: ${{ github.event.inputs.apiECredLogin || secrets.ECRED_API_CLIENT }}
          ECRED_API_SECRET_KEY: ${{ github.event.inputs.apiECredPass ||secrets.ECRED_API_SECRET_KEY }}
