name: Test PR

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: pip install awscli aws-sam-cli

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: npm install
      - run: npm run postinstall
      - run: npm test
